// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           18
// Async Callback:                       1
// Total number of exported functions:  20

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    elrond_wasm_sc_dns
    (
        canRegister
        register
        migrate
        resolve
        resolveFromHash
        getNameValueState
        claim
        setUpdateGasLimit
        getRegistrationCost
        getValueState
        getUpdateGasLimit
        getContractOwner
        getOwnShardId
        nameHash
        nameShard
        validateName
        version
        setFeatureFlag
        callBack
    )
}
