[package]
name = "multiversx-sc-sc-dns-abi"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@elrond.com>"]
edition = "2021"
publish = false
[dependencies.multiversx-sc-sc-dns]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.5"
