name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  checks: write
  pull-requests: write

jobs:
  contracts:
    name: Contracts
    uses: multiversx/mx-sc-actions/.github/workflows/contracts.yml@v2
    with:
      rust-toolchain: nightly-2022-12-08
      vmtools-version: v1.4.60
      install-libtinfo5: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
